export type DummyAccount = {
  id: string
  username: string
  full_name: string
  role: 'artist' | 'listener'
  genre: string
  bio: string
  avatar_color: string
  initials: string
  followers: string
  followersCount: number
  following: string
  followingCount: number
  tracks: number | null
  posts: number
  featured: boolean
  location: string
  website?: string
  joined: string
  dummyTracks?: { id: string; title: string; genre: string; plays: string; likes: string; date: string }[]
  dummyPosts?: { id: string; content: string; likes: string; comments: string; date: string }[]
}

export const DUMMY_ACCOUNTS: DummyAccount[] = [
  {
    id: 'dummy-1',
    username: 'auroravoss',
    full_name: 'Aurora Voss',
    role: 'artist',
    genre: 'Indie Electronic',
    bio: 'Crafting sonic landscapes one synth at a time. Berlin-based producer blending organic textures with electronic pulses. Featured on Pitchfork, NME.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'AV',
    followers: '12.4K',
    followersCount: 12400,
    following: '342',
    followingCount: 342,
    tracks: 38,
    posts: 91,
    featured: true,
    location: 'Berlin, Germany',
    website: 'auroravoss.music',
    joined: 'March 2023',
    dummyTracks: [
      { id: 'av1', title: 'Neon Bloom', genre: 'Indie Electronic', plays: '48.2K', likes: '3.1K', date: 'Jan 2026' },
      { id: 'av2', title: 'Glass Horizon', genre: 'Ambient', plays: '31.7K', likes: '2.4K', date: 'Nov 2025' },
      { id: 'av3', title: 'Pulse of Silence', genre: 'Electronica', plays: '19.0K', likes: '1.8K', date: 'Sep 2025' },
    ],
    dummyPosts: [
      { id: 'avp1', content: 'Just wrapped up the final mix for my new EP. Cannot wait to share it with you all 🎛️', likes: '842', comments: '67', date: 'Apr 2026' },
      { id: 'avp2', content: 'Berlin studio sessions have been unreal this week. The city inspires like nowhere else.', likes: '531', comments: '38', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-2',
    username: 'marcusbell',
    full_name: 'Marcus Bell',
    role: 'listener',
    genre: 'Hip-Hop • R&B',
    bio: 'Music is the soundtrack of my life. Always on the hunt for new sounds. Playlist curator & concert addict from Atlanta.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'MB',
    followers: '843',
    followersCount: 843,
    following: '1.2K',
    followingCount: 1200,
    tracks: null,
    posts: 24,
    featured: false,
    location: 'Atlanta, GA',
    joined: 'June 2024',
    dummyPosts: [
      { id: 'mbp1', content: 'Just discovered this underground R&B artist and my week is made. Pure emotion in every bar.', likes: '124', comments: '18', date: 'Apr 2026' },
      { id: 'mbp2', content: 'Saw Kendrick live last night. That man does NOT miss. Ever.', likes: '312', comments: '44', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-3',
    username: 'celestenoir',
    full_name: 'Celeste Noir',
    role: 'artist',
    genre: 'Dark Pop • Alternative',
    bio: 'Where shadows meet melody. Writing music for the misunderstood. Paris-born, London-made. Midnight is my golden hour.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'CN',
    followers: '31.2K',
    followersCount: 31200,
    following: '209',
    followingCount: 209,
    tracks: 72,
    posts: 148,
    featured: true,
    location: 'London, UK',
    website: 'celestenoir.co',
    joined: 'January 2022',
    dummyTracks: [
      { id: 'cn1', title: 'Velvet Abyss', genre: 'Dark Pop', plays: '102K', likes: '8.7K', date: 'Feb 2026' },
      { id: 'cn2', title: 'Porcelain Flames', genre: 'Alternative', plays: '87.4K', likes: '6.2K', date: 'Dec 2025' },
      { id: 'cn3', title: 'The Undoing', genre: 'Dark Pop', plays: '54.1K', likes: '4.9K', date: 'Oct 2025' },
    ],
    dummyPosts: [
      { id: 'cnp1', content: '"Velvet Abyss" hits 100K plays today. Thank you for letting my darkness into your ears 🖤', likes: '4.2K', comments: '301', date: 'Apr 2026' },
      { id: 'cnp2', content: 'Writing session at 3am. This is when the real songs are born.', likes: '2.1K', comments: '156', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-4',
    username: 'ryotanaka',
    full_name: 'Ryo Tanaka',
    role: 'listener',
    genre: 'Jazz • Lo-fi',
    bio: 'Vinyl collector. Coffee & lo-fi mornings. Savouring sound one record at a time. Tokyo → London.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'RT',
    followers: '2.1K',
    followersCount: 2100,
    following: '876',
    followingCount: 876,
    tracks: null,
    posts: 57,
    featured: false,
    location: 'London, UK',
    joined: 'September 2023',
    dummyPosts: [
      { id: 'rtp1', content: 'Finally found a first-press Blue Note Miles Davis at a record fair in Portobello. Life is good.', likes: '389', comments: '52', date: 'Apr 2026' },
      { id: 'rtp2', content: 'Sunday morning lo-fi playlist is up. Come decompress with me ☕', likes: '241', comments: '29', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-5',
    username: 'sagewinters',
    full_name: 'Sage Winters',
    role: 'artist',
    genre: 'Folk • Acoustic',
    bio: 'Stories told through strings. Nature, love, and the in-between. Self-produced in a cabin in Oregon.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'SW',
    followers: '8.7K',
    followersCount: 8700,
    following: '512',
    followingCount: 512,
    tracks: 24,
    posts: 63,
    featured: false,
    location: 'Portland, OR',
    joined: 'May 2023',
    dummyTracks: [
      { id: 'sw1', title: 'River & Rain', genre: 'Folk', plays: '22.1K', likes: '1.9K', date: 'Mar 2026' },
      { id: 'sw2', title: 'Cedar Song', genre: 'Acoustic', plays: '14.8K', likes: '1.3K', date: 'Jan 2026' },
    ],
    dummyPosts: [
      { id: 'swp1', content: 'Recorded "River & Rain" with just one mic and the cabin window open. You can hear the actual rain in the background.', likes: '931', comments: '74', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-6',
    username: 'destinycruz',
    full_name: 'Destiny Cruz',
    role: 'listener',
    genre: 'Pop • Dance',
    bio: "Concert addict. If it's got a beat, I'm already moving. Miami energy all day.",
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'DC',
    followers: '4.3K',
    followersCount: 4300,
    following: '2.1K',
    followingCount: 2100,
    tracks: null,
    posts: 89,
    featured: false,
    location: 'Miami, FL',
    joined: 'February 2024',
    dummyPosts: [
      { id: 'dcp1', content: 'Front row at Sabrina Carpenter and she pointed at me during Espresso. I blacked out.', likes: '1.2K', comments: '93', date: 'Apr 2026' },
      { id: 'dcp2', content: 'My summer playlist just hit 500 saves. Y\'all have good taste 🙌', likes: '612', comments: '41', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-7',
    username: 'neonpulse',
    full_name: 'Neon Pulse',
    role: 'artist',
    genre: 'Synthwave • Retrowave',
    bio: 'Bringing the 80s back one bassline at a time. Ride or die for the neon aesthetic. LA nights, cosmic vibes.',
    avatar_color: 'from-zinc-800 to-slate-700',
    initials: 'NP',
    followers: '54.1K',
    followersCount: 54100,
    following: '891',
    followingCount: 891,
    tracks: 113,
    posts: 204,
    featured: true,
    location: 'Los Angeles, CA',
    website: 'neonpulse.io',
    joined: 'October 2021',
    dummyTracks: [
      { id: 'np1', title: 'Chrome City', genre: 'Synthwave', plays: '218K', likes: '14.2K', date: 'Mar 2026' },
      { id: 'np2', title: 'Outrun Forever', genre: 'Retrowave', plays: '187K', likes: '11.8K', date: 'Jan 2026' },
      { id: 'np3', title: 'Drive Into the Grid', genre: 'Synthwave', plays: '143K', likes: '9.3K', date: 'Nov 2025' },
    ],
    dummyPosts: [
      { id: 'npp1', content: '"Chrome City" just crossed 200K plays. Built this one at 2am in a parking garage. Worth it.', likes: '8.4K', comments: '612', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-8',
    username: 'lilamontrose',
    full_name: 'Lila Montrose',
    role: 'artist',
    genre: 'R&B • Neo Soul',
    bio: 'Warm vocals, cold nights. Soul music for the modern heart. New Orleans raised, NYC based.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'LM',
    followers: '19.8K',
    followersCount: 19800,
    following: '431',
    followingCount: 431,
    tracks: 47,
    posts: 112,
    featured: false,
    location: 'New York, NY',
    joined: 'July 2022',
    dummyTracks: [
      { id: 'lm1', title: 'Honeydew', genre: 'Neo Soul', plays: '63.4K', likes: '5.1K', date: 'Feb 2026' },
      { id: 'lm2', title: 'Cigarette & Rain', genre: 'R&B', plays: '41.8K', likes: '3.7K', date: 'Dec 2025' },
    ],
    dummyPosts: [
      { id: 'lmp1', content: 'New Orleans taught me to feel music in my bones. NYC taught me to make it sharp. Both live in my songs.', likes: '2.3K', comments: '187', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-9',
    username: 'djkarsten',
    full_name: 'DJ Karsten',
    role: 'artist',
    genre: 'House • Techno',
    bio: 'Playing sets from Ibiza to Amsterdam. Drop the beat, lose yourself. Resident DJ @ Fabric London.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'DK',
    followers: '87.3K',
    followersCount: 87300,
    following: '1.1K',
    followingCount: 1100,
    tracks: 201,
    posts: 318,
    featured: true,
    location: 'Amsterdam, Netherlands',
    website: 'djkarsten.com',
    joined: 'August 2020',
    dummyTracks: [
      { id: 'dk1', title: 'Warehouse Protocol', genre: 'Techno', plays: '341K', likes: '22.1K', date: 'Apr 2026' },
      { id: 'dk2', title: 'Ibiza Sunrise', genre: 'House', plays: '289K', likes: '18.4K', date: 'Feb 2026' },
      { id: 'dk3', title: 'The 4am Set', genre: 'House', plays: '212K', likes: '14.7K', date: 'Dec 2025' },
    ],
    dummyPosts: [
      { id: 'dkp1', content: 'Fabric London last night was UNREAL. 2000 people, 6 hours, zero breaks. That\'s the church of house music.', likes: '12.1K', comments: '934', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-10',
    username: 'priyasharma',
    full_name: 'Priya Sharma',
    role: 'listener',
    genre: 'Indie • Alternative',
    bio: 'Playlist curator at heart. Every song tells a story. Finding the hidden gems so you don\'t have to.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'PS',
    followers: '1.6K',
    followersCount: 1600,
    following: '923',
    followingCount: 923,
    tracks: null,
    posts: 41,
    featured: false,
    location: 'Mumbai, India',
    joined: 'November 2024',
    dummyPosts: [
      { id: 'psp1', content: 'My "3am Indie" playlist just hit 1,000 followers on Spotify. Thank you for trusting my taste 🎧', likes: '284', comments: '33', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-11',
    username: 'leohartmann',
    full_name: 'Leo Hartmann',
    role: 'listener',
    genre: 'Metal • Prog Rock',
    bio: 'Headbanger by night, engineer by day. Never skip the guitar solo. Defender of long albums.',
    avatar_color: 'from-zinc-500 to-stone-700',
    initials: 'LH',
    followers: '967',
    followersCount: 967,
    following: '1.4K',
    followingCount: 1400,
    tracks: null,
    posts: 33,
    featured: false,
    location: 'Munich, Germany',
    joined: 'March 2025',
    dummyPosts: [
      { id: 'lhp1', content: 'Anyone who says metal isn\'t emotional has never listened to Tool\'s "Wings for Marie". I rest my case.', likes: '412', comments: '61', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-12',
    username: 'zoeadeyemi',
    full_name: 'Zoe Adeyemi',
    role: 'listener',
    genre: 'Afrobeats • World Music',
    bio: 'Music has no borders. Lagos roots, global ears. Dancing is my love language. 🌍',
    avatar_color: 'from-green-500 to-zinc-900',
    initials: 'ZA',
    followers: '3.8K',
    followersCount: 3800,
    following: '1.7K',
    followingCount: 1700,
    tracks: null,
    posts: 76,
    featured: false,
    location: 'Lagos, Nigeria',
    joined: 'April 2024',
    dummyPosts: [
      { id: 'zap1', content: 'Burna Boy at O2 Arena last night. That man carries Nigeria on his back and makes it look effortless. 🔥', likes: '1.8K', comments: '142', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-13',
    username: 'samokafor',
    full_name: 'Sam Okafor',
    role: 'listener',
    genre: 'Classical • Film Scores',
    bio: 'Hans Zimmer changed my life. Cinematic scores and morning runs. Finding beauty in orchestral chaos.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'SO',
    followers: '512',
    followersCount: 512,
    following: '678',
    followingCount: 678,
    tracks: null,
    posts: 19,
    featured: false,
    location: 'Toronto, Canada',
    joined: 'January 2025',
    dummyPosts: [
      { id: 'sop1', content: 'Interstellar soundtrack on vinyl while it\'s snowing outside. Peak human experience unlocked.', likes: '231', comments: '27', date: 'Mar 2026' },
    ],
  },
  {
    id: 'dummy-14',
    username: 'mirachen',
    full_name: 'Mira Chen',
    role: 'artist',
    genre: 'Classical • Neo-Classical',
    bio: 'Piano, cello, and the occasional electric guitar. Conservatory trained, genre-fluid. Performing at the intersection of old and new.',
    avatar_color: 'from-slate-400 to-slate-600',
    initials: 'MC',
    followers: '6.2K',
    followersCount: 6200,
    following: '318',
    followingCount: 318,
    tracks: 19,
    posts: 44,
    featured: false,
    location: 'Vienna, Austria',
    joined: 'February 2023',
    dummyTracks: [
      { id: 'mc1', title: 'Adagio for the Restless', genre: 'Neo-Classical', plays: '28.4K', likes: '2.3K', date: 'Jan 2026' },
      { id: 'mc2', title: 'Nocturne No. 7', genre: 'Classical', plays: '19.1K', likes: '1.7K', date: 'Oct 2025' },
    ],
    dummyPosts: [
      { id: 'mcp1', content: 'Performed at Konzerthaus Wien last night. The acoustics in that hall are something I\'ll never take for granted.', likes: '1.1K', comments: '88', date: 'Apr 2026' },
    ],
  },
  {
    id: 'dummy-15',
    username: 'axeldrummond',
    full_name: 'Axel Drummond',
    role: 'artist',
    genre: 'Rock • Grunge',
    bio: 'Loud guitars. Louder feelings. Pacific Northwest born and raised. Guitar tone is everything.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'AD',
    followers: '22.0K',
    followersCount: 22000,
    following: '743',
    followingCount: 743,
    tracks: 56,
    posts: 131,
    featured: false,
    location: 'Seattle, WA',
    joined: 'April 2022',
    dummyTracks: [
      { id: 'ad1', title: 'Static Rain', genre: 'Grunge', plays: '71.3K', likes: '5.8K', date: 'Mar 2026' },
      { id: 'ad2', title: 'Broken Filament', genre: 'Rock', plays: '52.4K', likes: '4.2K', date: 'Dec 2025' },
      { id: 'ad3', title: 'The Weight of Grey', genre: 'Alternative Rock', plays: '38.9K', likes: '3.1K', date: 'Sep 2025' },
    ],
    dummyPosts: [
      { id: 'adp1', content: 'Recorded "Static Rain" on a Fender Jaguar through a busted Fender Twin. The imperfection is the point.', likes: '3.4K', comments: '278', date: 'Mar 2026' },
    ],
  },
  {
    id: 'pop-1',
    username: 'alexjohns',
    full_name: 'Alex Johnson',
    role: 'artist',
    genre: 'Electronic & Synth-pop',
    bio: 'Electronic & synth-pop producer crafting infectious hooks and lush soundscapes. Berlin-trained, globally recognised.',
    avatar_color: 'from-slate-600 to-zinc-900',
    initials: 'AJ',
    followers: '12.5K',
    followersCount: 12543,
    following: '210',
    followingCount: 210,
    tracks: 64,
    posts: 143,
    featured: true,
    location: 'New York, NY',
    website: 'alexjohnson.music',
    joined: 'January 2021',
    dummyTracks: [
      { id: 'aj1', title: 'Synthetic Dream', genre: 'Synth-pop', plays: '98.4K', likes: '7.2K', date: 'Mar 2026' },
      { id: 'aj2', title: 'Neon Pulse Redux', genre: 'Electronic', plays: '71.1K', likes: '5.4K', date: 'Jan 2026' },
    ],
    dummyPosts: [
      { id: 'ajp1', content: 'Finished mastering the new album at 4am. Six months of work in 42 minutes. Proud of this one.', likes: '3.1K', comments: '214', date: 'Apr 2026' },
    ],
  },
  {
    id: 'pop-2',
    username: 'lunawaves',
    full_name: 'Luna Waves',
    role: 'artist',
    genre: 'Singer-songwriter & Producer',
    bio: 'Singer-songwriter & producer. Writing confessional pop with cinematic production. LA based, globally inspired.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'LW',
    followers: '10.2K',
    followersCount: 10234,
    following: '318',
    followingCount: 318,
    tracks: 41,
    posts: 97,
    featured: false,
    location: 'Los Angeles, CA',
    website: 'lunawaves.co',
    joined: 'March 2022',
    dummyTracks: [
      { id: 'lw1', title: 'Tides of You', genre: 'Indie Pop', plays: '77.2K', likes: '6.1K', date: 'Feb 2026' },
    ],
    dummyPosts: [
      { id: 'lwp1', content: 'Wrote Tides of You in 20 minutes on a Tuesday. Sometimes the songs just fall out of you.', likes: '2.4K', comments: '189', date: 'Apr 2026' },
    ],
  },
  {
    id: 'pop-3',
    username: 'jazzvibes',
    full_name: 'Jazz Vibes',
    role: 'artist',
    genre: 'Jazz & Fusion',
    bio: 'Jazz & fusion specialist. Blending classic traditions with modern production. Live performance is everything.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'JV',
    followers: '8.8K',
    followersCount: 8756,
    following: '401',
    followingCount: 401,
    tracks: 33,
    posts: 78,
    featured: false,
    location: 'New Orleans, LA',
    joined: 'June 2021',
    dummyTracks: [
      { id: 'jv1', title: 'Midnight Bebop', genre: 'Jazz', plays: '44.1K', likes: '3.8K', date: 'Mar 2026' },
    ],
    dummyPosts: [
      { id: 'jvp1', content: 'Live session at Preservation Hall tonight. Jazz is not dead, it never sleeps.', likes: '1.6K', comments: '112', date: 'Apr 2026' },
    ],
  },
  {
    id: 'pop-4',
    username: 'djstudio',
    full_name: 'DJ Studio',
    role: 'artist',
    genre: 'House & Electronic',
    bio: 'House & electronic DJ and producer. From underground club nights to festival stages.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'DS',
    followers: '7.9K',
    followersCount: 7890,
    following: '543',
    followingCount: 543,
    tracks: 89,
    posts: 167,
    featured: false,
    location: 'Chicago, IL',
    joined: 'September 2020',
    dummyTracks: [
      { id: 'ds1', title: 'Acid Frequency', genre: 'House', plays: '61.3K', likes: '4.9K', date: 'Mar 2026' },
    ],
    dummyPosts: [
      { id: 'dsp1', content: 'Played a 5-hour set last night and only touched the surface. The vinyl is life.', likes: '2.1K', comments: '156', date: 'Apr 2026' },
    ],
  },
  {
    id: 'pop-5',
    username: 'echosound',
    full_name: 'Echo Sound',
    role: 'artist',
    genre: 'Ambient & Experimental',
    bio: 'Ambient & experimental music. Creating sonic environments between sound and silence. Portland based.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'ES',
    followers: '6.5K',
    followersCount: 6543,
    following: '289',
    followingCount: 289,
    tracks: 27,
    posts: 54,
    featured: false,
    location: 'Portland, OR',
    joined: 'November 2021',
    dummyTracks: [
      { id: 'es1', title: 'Dissolve', genre: 'Ambient', plays: '38.7K', likes: '3.2K', date: 'Feb 2026' },
    ],
    dummyPosts: [
      { id: 'esp1', content: 'Recorded the rain tonight through a contact mic on the window. Will be on the next album.', likes: '1.3K', comments: '94', date: 'Mar 2026' },
    ],
  },
  {
    id: 'pop-6',
    username: 'synthwave',
    full_name: 'Synth Wave',
    role: 'artist',
    genre: 'Retro Synth & Vaporwave',
    bio: 'Retro synth & vaporwave. Channelling the ghost of the 80s through modern production. Aesthetics are everything.',
    avatar_color: 'from-zinc-800 to-zinc-900',
    initials: 'SW2',
    followers: '5.4K',
    followersCount: 5432,
    following: '178',
    followingCount: 178,
    tracks: 51,
    posts: 88,
    featured: false,
    location: 'Miami, FL',
    joined: 'May 2022',
    dummyTracks: [
      { id: 'sw3', title: 'Pastel Sky Drive', genre: 'Vaporwave', plays: '52.1K', likes: '4.3K', date: 'Mar 2026' },
    ],
    dummyPosts: [
      { id: 'swp2', content: 'The 80s never ended. They just moved into the cloud.', likes: '1.7K', comments: '131', date: 'Apr 2026' },
    ],
  },
]

export function getDummyAccount(username: string): DummyAccount | null {
  return DUMMY_ACCOUNTS.find(a => a.username === username) ?? null
}
